"use client";
import { useState } from "react";
import { ArrowDownAZ, Check, Pencil, RefreshCw, Search, ShieldCheck, X } from "lucide-react";
import type { ManagedUser, UserResult } from "@/features/users/schemas";
import { UserEditor, type SaveUser, type DeleteUser } from "./user-editor";
import { statusLabels } from "./account-status-select";
const filters=[['all','Todos'],['pending','Pendentes'],['approved','Aprovados'],['rejected','Rejeitados'],['suspended','Suspensos']] as const;
export type UsersPanelProps={initialUsers:ManagedUser[];currentUserId:string;initialError?:string;onSave:SaveUser;onDelete:DeleteUser;onRefresh:()=>Promise<UserResult<{users:ManagedUser[]}>>};
export function UsersPanel({initialUsers,currentUserId,initialError="",onSave,onDelete,onRefresh}:UsersPanelProps) {
  const [users,setUsers]=useState(initialUsers),[filter,setFilter]=useState<string>("all"),[search,setSearch]=useState(""),[ascending,setAscending]=useState(true);
  const [editing,setEditing]=useState<ManagedUser|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(initialError);
  const visible=users.filter(user=>(filter==="all"||user.status===filter)&&`${user.full_name} ${user.email}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))).sort((a,b)=>(ascending?1:-1)*a.full_name.localeCompare(b.full_name,"pt-BR"));
  const save:SaveUser=async(id,changes)=>{const result=await onSave(id,changes);if(result.ok)setUsers(previous=>previous.map(user=>user.id===id?result.user:user));return result;};
  const remove:DeleteUser=async(id)=>{const result=await onDelete(id);if(result.ok)setUsers(previous=>previous.filter(user=>user.id!==id));return result;};
  async function refresh() {if(busy)return;setBusy(true);setError("");try {const result=await onRefresh();if(result.ok)setUsers(result.users);else setError(result.message);}catch{setError("Não foi possível atualizar. Tente novamente.");}finally{setBusy(false);}}
  async function approve(user:ManagedUser) {if(busy)return;setBusy(true);setError("");try{const result=await save(user.id,{status:"approved",permissions:{...user.permissions,can_view:true}});if(!result.ok)setError(result.message);}catch{setError("Não foi possível aprovar. Tente novamente.");}finally{setBusy(false);}}
  return <main className="users-workspace"><header className="workspace-heading"><div><span className="eyebrow workspace-eyebrow"><ShieldCheck size={14}/>Administração</span><h1>Usuários e permissões</h1><p>Aprove acessos e defina o que cada pessoa pode fazer no Calendário F1.</p></div><button className="button-quiet" disabled={busy} onClick={refresh}><RefreshCw size={15}/>{busy?"Atualizando…":"Atualizar"}</button></header>
    <section className="panel users-filters" aria-label="Filtros de usuários"><div className="users-filter-chips">{filters.map(([key,label])=><button key={key} className={`filter-chip ${filter===key?"active":""}`} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}{" "}<span>{key==="all"?users.length:users.filter(user=>user.status===key).length}</span></button>)}</div><div className="users-search-row"><div className="users-search"><Search size={17}/><input type="search" aria-label="Buscar por nome ou e-mail" placeholder="Buscar por nome ou e-mail" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button className="users-search-clear" aria-label="Limpar busca" onClick={()=>setSearch("")}><X size={15}/></button>}</div><button className="button-quiet" aria-label={ascending?"Ordenar Z–A":"Ordenar A–Z"} onClick={()=>setAscending(!ascending)}><ArrowDownAZ size={17}/>{ascending?"A–Z":"Z–A"}</button></div></section>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <section className="panel users-list" aria-label="Lista de usuários" aria-busy={busy}><div className="user-row users-table-heading" aria-hidden="true"><span>Usuário</span><span>E-mail</span><span>Perfil</span><span>Status</span><span>Ações</span></div>
      {!visible.length&&<p className="users-empty">{error?"A lista não pôde ser carregada. Use Atualizar para tentar novamente.":"Nenhum usuário encontrado para este filtro."}</p>}
      {visible.map(user=><article className="user-row" key={user.id}><div className="users-identity"><span className="users-avatar" aria-hidden="true">{(user.full_name.trim()||user.email).slice(0,2).toUpperCase()}</span><div><strong>{user.full_name||"Sem nome"}</strong>{user.id===currentUserId&&<small>Sua conta</small>}</div></div><span className="users-email" title={user.email}>{user.email}</span><span className={`users-role ${user.role==="owner"?"users-role-owner":""}`}>{user.role==="owner"?"Owner":"Membro"}</span><span className={`status-badge status-${user.status}`}>{statusLabels[user.status]}</span><div className="users-row-actions">{user.status==="pending"&&user.role!=="owner"&&user.id!==currentUserId&&<button className="icon-button users-approve" aria-label={`Aprovar ${user.full_name}`} title="Aprovar com acesso ao próprio calendário" disabled={busy} onClick={()=>approve(user)}><Check size={16}/></button>}<button className="icon-button" aria-label={`Editar ${user.full_name}`} disabled={busy} onClick={()=>setEditing(user)}><Pencil size={15}/></button></div></article>)}
    </section><p className="users-list-note">Pendentes são solicitações de acesso. Aprovados são usuários ativos; rejeitados e suspensos não acessam o calendário.</p>
    {editing&&<UserEditor key={editing.id} user={editing} currentUserId={currentUserId} onSave={save} onDelete={remove} onClose={()=>setEditing(null)}/>}
  </main>;
}
