// @vitest-environment node
import { beforeEach, describe, expect, it, vi } from "vitest";
import { incidentBackend } from "../support/incident-backend";
import { listIncidentsForMonth, createIncident, updateIncident, deleteIncident } from "@/features/incidents/actions";
const boundary = vi.hoisted(() => ({ client: null as unknown, revalidate: vi.fn() }));
vi.mock("@/lib/supabase/server", () => ({ createServerSupabaseClient: async () => boundary.client }));
vi.mock("next/cache", () => ({ revalidatePath: boundary.revalidate }));
let backend: ReturnType<typeof incidentBackend>;
const input = { date: "2026-09-02", kind: "partial", startTime: "10:00", endTime: "10:20", note: "  F1 caiu  " };
const id = "33333333-3333-4333-8333-333333333333";
const other = "44444444-4444-4444-8444-444444444444";
function row(author: string | null, date = "2026-09-02", rowId = id) { return { id: rowId, author_id: author, incident_date: date, kind: "partial", start_time: "10:00:00", end_time: "10:20:00", note: "Registro persistido" }; }
beforeEach(() => { backend = incidentBackend(); boundary.client = backend.client; boundary.revalidate.mockClear(); });

describe("persisted incident actions", () => {
  it("requires a verified session even for direct action requests", async () => { backend.state.user = null; expect(await createIncident(input)).toMatchObject({ ok: false, code: "unauthenticated" }); expect(backend.state.rows).toEqual([]); });
  it.each(["pending", "rejected", "suspended"])("rejects %s writers with all flags", async (status) => { backend.state.status = status; expect(await createIncident(input)).toMatchObject({ ok: false, code: "forbidden" }); });
  it.each(["can_create", "can_edit", "can_delete"] as const)("enforces %s on the server", async (flag) => { backend.state.flags[flag] = false; const result = flag === "can_create" ? await createIncident(input) : flag === "can_edit" ? await updateIncident(id, input) : await deleteIncident(id); expect(result).toMatchObject({ ok: false, code: "forbidden" }); });
  it("validates reversed intervals before writing", async () => { expect(await createIncident({ ...input, endTime: "09:00" })).toMatchObject({ ok: false, code: "validation" }); expect(backend.state.writes).toEqual([]); });
  it("persists normalized fields and returns server-assigned identity", async () => { const result = await createIncident({ ...input, authorId: other, id: other }); expect(result).toMatchObject({ ok: true, incident: { authorId: backend.state.user!.id, note: "F1 caiu", date: input.date } }); expect(backend.state.writes).toEqual([{ incident_date: input.date, kind: "partial", start_time: "10:00", end_time: "10:20", note: "F1 caiu" }]); expect(boundary.revalidate).toHaveBeenCalledWith("/calendar"); });
  it("persists full-day records with null times", async () => { expect(await createIncident({ ...input, kind: "full_day", startTime: null, endTime: null })).toMatchObject({ ok: true, incident: { kind: "full_day", startTime: null, endTime: null } }); });
  it("filters the month and creator before calculating the visible result", async () => { backend.state.rows = [row(backend.state.user!.id), row(other), row(backend.state.user!.id, "2026-08-31"), row(backend.state.user!.id, "2026-10-01")]; const result = await listIncidentsForMonth(2026, 9); expect(result).toMatchObject({ ok: true, incidents: [{ authorId: backend.state.user!.id, startTime: "10:00", endTime: "10:20" }] }); expect(backend.state.filters).toEqual(expect.arrayContaining([["eq", "author_id", backend.state.user!.id], ["gte", "incident_date", "2026-09-01"], ["lte", "incident_date", "2026-09-30"]])); });
  it("allows view-all without changing mutation flags and maps deleted authors", async () => { backend.state.flags.can_view_all = true; backend.state.flags.can_edit = false; backend.state.rows = [row(other), row(null, "2026-09-03", other)]; expect(await listIncidentsForMonth(2026, 9)).toMatchObject({ ok: true, incidents: [{ authorId: other }, { authorId: null }] }); expect(await updateIncident(id, input)).toMatchObject({ ok: false, code: "forbidden" }); });
  it("owner sees and updates all rows despite false flags", async () => { backend.state.role = "owner"; backend.state.flags.can_view_all = false; backend.state.flags.can_edit = false; backend.state.rows = [row(other)]; expect(await updateIncident(id, input)).toMatchObject({ ok: true, incident: { note: "F1 caiu", authorId: other } }); });
  it("does not update or delete another creator's hidden row", async () => { backend.state.rows = [row(other)]; expect(await updateIncident(id, input)).toMatchObject({ ok: false, code: "not_found" }); expect(await deleteIncident(id)).toMatchObject({ ok: false, code: "not_found" }); expect(backend.state.rows[0].note).toBe("Registro persistido"); expect(boundary.revalidate).not.toHaveBeenCalled(); });
  it("updates and deletes an owned row only after returned-row confirmation", async () => { backend.state.rows = [row(backend.state.user!.id)]; expect(await updateIncident(id, input)).toMatchObject({ ok: true, incident: { note: "F1 caiu" } }); expect(await deleteIncident(id)).toMatchObject({ ok: true, id }); expect(backend.state.rows).toEqual([]); });
  it.each(["23P01", "23505"])("turns database conflict %s into a safe recoverable error", async (code) => { backend.state.error = { code, message: "secret database detail" }; const result = await createIncident(input); expect(result).toMatchObject({ ok: false, code: "conflict" }); expect(JSON.stringify(result)).not.toContain("secret"); expect(boundary.revalidate).not.toHaveBeenCalled(); });
  it("fails gracefully without Supabase configuration", async () => { boundary.client = null; expect(await listIncidentsForMonth(2026, 9)).toMatchObject({ ok: false }); });
  it("rejects invalid months and forged IDs without persistence", async () => { expect(await listIncidentsForMonth(2026, 13)).toMatchObject({ ok: false, code: "validation" }); expect(await deleteIncident("arbitrary")).toMatchObject({ ok: false, code: "validation" }); });
  it("paginates beyond a single API page without truncating monthly metrics", async () => { backend.state.rows = Array.from({ length: 1001 }, (_, index) => row(backend.state.user!.id, "2026-09-02", `row-${index}`)); const result = await listIncidentsForMonth(2026, 9); expect(result.ok && result.incidents.length).toBe(1001); });
});
